
# python installed on remote
ansible_python_interpreter: /usr/bin/python3

# Kubernetes configuration
kubernetes:
  # cluster name
  clusterName: kubernetes-cluster
  # list of main Kubernetes component
  components:
    cri:
      version: v1.18.0
    cni:
      version: v0.8.6
    etcd:
      version: v3.4.10
    runc:
      version: v1.0.0-rc91
    containerd:
      version: 1.3.6
  # list of addons Kubernetes component
  addonsComponents:
    # Kubernetes cluster will use different resolv.conf
    # with the node
    coredns:
      nameservers:
        - 172.30.0.3
      version: 1.7.0
    # flannel interface, most Kubernetes installation using
    # single interface, this enabled to use different interface
    # TODO: support flannel tunneling on different interface as API
    flannel:
      interface: eth1
      version: v0.12.0
    # enabled metrics server
    # add flags for metrics server
    metricsServer:
      enabled: true
      version: v0.3.7
    # enabled oidc
    # add flags for oidc
    oidc:
      enabled: true
      issuerURL: https://keycloak.zufar.io:8443/auth/realms/IAM
      clientID: kubernetes
      groupsClaim: user_groups
      usernameClaim: preferred_username
      groupsPrefix: "oidc:"
      usernamePrefix: "oidc:"
  certificate:
    # directory created in deployer node for certificate
    directory: ~/kubernetes-certificate
    # create client kubeconfig
    # will be generated in the certificate directory
    createClientKubeconfig: true
  # number of Kubernetes master
  masterNumber: 3
  version: v1.18.6

# Infrastructure configuration
infrastructure:
  ca:
    city: Jakarta
    country: ID
    organizationUnit: Kubernetes
    province: Jakarta
  keepalived:
    # IP of one of the Kubernetes master
    # this will be the default master for keepalived
    masterIP: 10.200.100.10
    # Keepalived interface
    # mostly using interface where the API listen
    interface: eth1
    # Keepalived routerID
    routerID: 50
    # Virtual IP for Kubernetes API
    virtualIP: 10.200.100.100
    # Virtual Port for Kubernetes API
    virtualIPPort: 64430

# user on all nodes
user: vagrant
