
ansible_python_interpreter: /usr/bin/python3
kubernetes_version: v1.13.3
cri_version: v1.13.0
cni_version: v0.6.0
coredns_version: 1.2.5
kubernetes_master_number: 3

virtual_ip: 10.202.202.100
virtual_ip_k8s_port: 64430

max_pod_per_node: 110

#  "System reserved" should include the amount of memory covered by the eviction threshold.
reserve_memory_utilization: 1.5Gi
evicted_pod_when_memory_less_than: 500Mi
