- name: pause 1 minute
  pause:
    minutes: 1

- name: create rbac from template
  template:
    src: "rbac.yaml.j2"
    dest: "~/rbac.yaml"
  when: inventory_hostname == '{{ keepalived_master }}'
- name: apply rbac template
  shell: kubectl create -f ~/rbac.yaml
  when: inventory_hostname == '{{ keepalived_master }}'
