- name: Copy cert
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
  with_items:
    - { src: '/home/{{ user }}/{{ inventory_hostname }}-key.pem', dest: '/var/lib/kubelet/{{ inventory_hostname }}-key.pem' }
    - { src: '/home/{{ user }}/{{ inventory_hostname }}.pem', dest: '/var/lib/kubelet/{{ inventory_hostname }}.pem' }
    - { src: '/home/{{ user }}/{{ inventory_hostname }}.kubeconfig', dest: '/var/lib/kubelet/kubeconfig' }
    - { src: '/home/{{ user }}/ca.pem', dest: '/var/lib/kubernetes/ca.pem' }
    - { src: '/home/{{ user }}/kube-proxy.kubeconfig', dest: '/var/lib/kube-proxy/kubeconfig' }

- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart kube-proxy
  systemd:
    name: kube-proxy
    state: restarted
    daemon_reload: yes
    enabled: yes


