- name: Copy cert
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
    mode: 400
  with_items:
    - { src: '/home/{{ user }}/ca.pem', dest: '/etc/etcd/ca.pem' }
    - { src: '/home/{{ user }}/kubernetes-key.pem', dest: '/etc/etcd/kubernetes-key.pem' }
    - { src: '/home/{{ user }}/kubernetes.pem', dest: '/etc/etcd/kubernetes.pem' }

- name: restart etcd
  systemd:
    name: etcd
    state: restarted
    daemon_reload: yes
    enabled: yes
