- name: Copy cert
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
    mode: 400
  with_items:
    - { src: '/home/{{ user }}/kube-etcd.pem', dest: '/etc/etcd/kube-etcd.pem' }
    - { src: '/home/{{ user }}/kube-etcd-key.pem', dest: '/etc/etcd/kube-etcd-key.pem' }
    - { src: '/home/{{ user }}/kube-etcd-peer.pem', dest: '/etc/etcd/kube-etcd-peer.pem' }
    - { src: '/home/{{ user }}/kube-etcd-peer-key.pem', dest: '/etc/etcd/kube-etcd-peer-key.pem' }

- name: restart etcd
  systemd:
    name: etcd
    state: restarted
    daemon_reload: yes
    enabled: yes
