#
# This roles generate CA & kubeconfig in deployer node
# deployer node send the CA & kubeconfig into all nodes
#
- name: generate CA & kubeconfig
  become: true
  hosts: deployer
  roles:
    - initial-setup

#
# This roles setup etcd cluster in etcd group ansible
# you can merge etcd into master
# by changing etcd group IP into master IP
#
- name: Setup etcd cluster
  become: true
  hosts: etcd
  roles:
    - etcd-cluster

#
# This roles setup haproxy keepalived in master node
# and setup master cluster
#
- name: Setup Master Cluter
  become: true
  hosts: master
  roles:
    - haproxy-keepalived
    - master-cluster

#
# This roles setup worker cluster in master & worker node
#
- name: Setup Worker
  become: true
  hosts: worker,master
  roles:
    - worker-cluster

#
# this roles setup CNI, DNS, and taint master node
#
- name: Setup CNI & core-dns
  become: true
  hosts: master
  roles:
    - cni-dns



