- name: generate CA & kubeconfig
  hosts: deployer
  roles:
    - initial_setup

- name: Setup etcd cluster
  hosts: etcd
  roles:
    - etcd_cluster

- name: Setup haproxy & keepalived
  hosts: master
  roles:
    - haproxy-keepalived