- name: generate CA & kubeconfig
  hosts: deployer
  roles:
    - initial-setup

- name: Setup etcd cluster
  hosts: etcd
  roles:
    - etcd-cluster

- name: Setup Master Cluter
  hosts: master
  roles:
    - haproxy-keepalived
    - master-cluster

- name: Setup Worker
  hosts: master
  roles:
    - worker-cluster