#############################
##### Renew Certificate #####
#############################
#
# run this roles if certificate is expired
#

- name: renew Certificate
  hosts: deployer
  roles:
    - renew-certificate

#
# restarting service kubernetes etcd
# systemctl restart etcd
#
# restarting service kubernetes master
# systemctl restart kube-apiserver
# systemctl restart kube-scheduler
# systemctl restart kube-controller-manager
# systemctl restart kubelet
# systemctl restart kube-proxy
#
# restarting service kubernetes worker
# systemctl restart kubelet
# systemctl restart kube-proxy
#