---
- name: copy kube-proxy
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - { src: 'kube-proxy-csr.json.j2', dest: '{{ kubernetes.certificate.directory }}/kube-proxy-csr.json' }

- name: copy master certificate
  template:
    src: "master-csr.json.j2"
    dest: "{{ kubernetes.certificate.directory }}/{{ item }}-csr.json"
  with_items: "{{ groups['master'] }}"

- name: copy worker certificate
  template:
    src: "worker-csr.json.j2"
    dest: "{{ kubernetes.certificate.directory }}/{{ item }}-csr.json"
  with_items: "{{ groups['worker'] }}"

# used in kube-proxy kubeconfig
- name: generate kube-proxy certificate
  args:
    chdir: "{{ kubernetes.certificate.directory }}"
  shell: |
    cfssl gencert \
    -ca=ca.pem \
    -ca-key=ca-key.pem \
    -config=ca-config.json \
    -profile=kubernetes \
    kube-proxy-csr.json | cfssljson -bare kube-proxy

# used in kubelet master config
- name: generate master certificate
  args:
    chdir: "{{ kubernetes.certificate.directory }}"
  shell: |
    cfssl gencert \
    -ca=ca.pem \
    -ca-key=ca-key.pem \
    -config=ca-config.json \
    -hostname={{ item }} \
    -profile=kubernetes \
    {{ item }}-csr.json | cfssljson -bare {{ item }}
  with_items: "{{ groups['master'] }}"

# used in kubelet worker config
- name: generate worker certificate
  args:
    chdir: "{{ kubernetes.certificate.directory }}"
  shell: |
    cfssl gencert \
    -ca=ca.pem \
    -ca-key=ca-key.pem \
    -config=ca-config.json \
    -hostname={{ item }} \
    -profile=kubernetes \
    {{ item }}-csr.json | cfssljson -bare {{ item }}
  with_items: "{{ groups['worker'] }}"

- name: copy cert into master node
  vars:
    master_ip: "{{ groups['master'] | join(' ') }}"
  args:
    chdir: "{{ kubernetes.certificate.directory }}"
  shell: |
    for instance in {{ master_ip }}; do
      # copy root CA
      scp ca.pem {{ user }}@${instance}:~/

      # copy master kubelet certificate
      scp ${instance}-key.pem {{ user }}@${instance}:~/
      scp ${instance}.pem {{ user }}@${instance}:~/
    done

- name: copy cert into worker node
  vars:
    worker_ip: "{{ groups['worker'] | join(' ') }}"
  args:
    chdir: "{{ kubernetes.certificate.directory }}"
  shell: |
    for instance in {{ worker_ip }}; do
      # copy root CA
      scp ca.pem {{ user }}@${instance}:~/

      # copy worker kubelet certificate
      scp ${instance}-key.pem {{ user }}@${instance}:~/
      scp ${instance}.pem {{ user }}@${instance}:~/
    done


