- name: pause 1 minute
  pause:
    minutes: 1

- name: create core-dns from template
  template:
    src: "core-dns.yaml.j2"
    dest: "~/core-dns.yaml"
  when: inventory_hostname == '{{ keepalived_master }}'
  
- name: apply core-dns template
  shell: kubectl create -f ~/core-dns.yaml
  when: inventory_hostname == '{{ keepalived_master }}'
