---
- name: Generate random key
  shell: "head -c 32 /dev/urandom | base64"
  register: random_key_raw

- name: set variable 
  set_fact:
    random_key: "{{ random_key_raw.stdout }}"

- name: copy data encryption template
  template:
    src: "encryption-config.yml.j2"
    dest: "{{ kubernetes.certificate.directory }}/encryption-config.yml"

- name: copy into master node
  vars:
    master_ip: "{{ groups['master'] | join(' ') }}"
  args:
    chdir: "{{ kubernetes.certificate.directory }}"
  shell: |
    for instance in {{ master_ip }}; do
      scp encryption-config.yml {{ user }}@${instance}:~/
    done

  