---
- include: install-requirement.yml
- include: generate-ca.yml
  become: yes
  become_user: "{{ user }}"
- include: generate-kubeconfig.yml
  become: yes
  become_user: "{{ user }}"
- include: generate-data-encryption.yml
  become: yes
  become_user: "{{ user }}"