- name: Copy cert
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
    mode: 400
  with_items:
    - { src: '/home/{{ user }}/kube-apiserver-etcd-client.pem', dest: '/var/lib/kubernetes/kube-apiserver-etcd-client.pem' }
    - { src: '/home/{{ user }}/kube-apiserver-etcd-client-key.pem', dest: '/var/lib/kubernetes/kube-apiserver-etcd-client-key.pem' }
    - { src: '/home/{{ user }}/kube-apiserver-kubelet-client.pem', dest: '/var/lib/kubernetes/kube-apiserver-kubelet-client.pem' }
    - { src: '/home/{{ user }}/kube-apiserver-kubelet-client-key.pem', dest: '/var/lib/kubernetes/kube-apiserver-kubelet-client-key.pem' }
    - { src: '/home/{{ user }}/front-proxy-client.pem', dest: '/var/lib/kubernetes/front-proxy-client.pem' }
    - { src: '/home/{{ user }}/front-proxy-client-key.pem', dest: '/var/lib/kubernetes/front-proxy-client-key.pem' }
    - { src: '/home/{{ user }}/kube-controller-manager.kubeconfig', dest: '/var/lib/kubernetes/kube-controller-manager.kubeconfig' }
    - { src: '/home/{{ user }}/kube-scheduler.kubeconfig', dest: '/var/lib/kubernetes/kube-scheduler.kubeconfig' }
    - { src: '/home/{{ user }}/admin.kubeconfig', dest: '/root/.kube/config' }

- name: restart kube-apiserver
  systemd:
    name: kube-apiserver
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart kube-controller-manager
  systemd:
    name: kube-controller-manager
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart kube-scheduler
  systemd:
    name: kube-scheduler
    state: restarted
    daemon_reload: yes
    enabled: yes




