- name: pause 1 minute
  pause:
    minutes: 1

- name: create core-dns from template
  template:
    src: "core-dns.yml.j2"
    dest: "~/core-dns.yml"
  when: inventory_hostname == '{{ infrastructure.keepalived.masterIP }}'
  
- name: apply core-dns template
  shell: kubectl apply -f ~/core-dns.yml
  when: inventory_hostname == '{{ infrastructure.keepalived.masterIP }}'
